
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-org0app0
spec:
  template:
    spec:
      containers:
      - name: apporg0app0
        env:
          - name: PAGE_SIZE
            value: "10"
            